export const emotionList = [
  'Love',
  'Joy',
  'Surprise',
  'Sadness',
  'Anger',
  'Fear',
  'Peaceful',
  'Tenderness',
  'Desire',
  'Longing',
  'Affectionate',
  'Enthralled',
  'Elation',
  'Enthusiastic',
  'Optimistic',
  'Proud',
  'Cheerful',
  'Happy',
  'Content',
  'Moved',
  'Overcome',
  'Amazed',
  'Confused',
  'Stunned',
  'Despair',
  'Neglected',
  'Shameful',
  'Disappointed',
  'Suffering',
  'Disgust',
  'Envy',
  'Irritable',
  'Exasperated',
  'Rage',
  'Horror',
  'Nervous',
  'Insecure',
  'Terror',
  'Scared',
  'Satisfied',
  'Relieved',
  'Compassionate',
  'Caring',
  'Infatuation',
  'Passion',
  'Attracted',
  'Sentimental',
  'Fondness',
  'Romantic',
  'Rapture',
  'Enchanted',
  'Jubilation',
  'Euphoric',
  'Zeal',
  'Excited',
  'Hopeful',
  'Eager',
  'Illustrious',
  'Triumphant',
  'Blissful',
  'Jovial',
  'Delighted',
  'Amused',
  'Satisfied',
  'Pleased',
  'Touched',
  'Stimulated',
  'Astounded',
  'Speechless',
  'Awe-struck',
  'Astonished',
  'Perplexed',
  'Disillusioned',
  'Dismayed',
  'Shocked',
  'Powerless',
  'Grief',
  'Lonely',
  'Isolated',
  'Guilty',
  'Regretful',
  'Displeased',
  'Dismayed',
  'Sorrow',
  'Depressed',
  'Hurt',
  'Agony',
  'Revolted',
  'Contempt',
  'Jealous',
  'Resentful',
  'Aggravated',
  'Annoyed',
  'Frustrated',
  'Agitated',
  'Hostile',
  'Hate',
  'Dread',
  'Mortified',
  'Anxious',
  'Worried',
  'Inadequate',
  'Inferior',
  'Hysterical',
  'Panic',
  'Helpless',
  'Frightened',
];

export const emotionColor = [
  { emotion: 'Love', color: '' },
  { emotion: 'Joy', color: '' },
  { emotion: 'Surprise', color: '' },
  { emotion: 'Sadness', color: '' },
  { emotion: 'Anger', color: '' },
  { emotion: 'Fear', color: '' },
  { emotion: 'Peaceful', color: '' },
  { emotion: 'Tenderness', color: '' },
  { emotion: 'Desire', color: '' },
  { emotion: 'Longing', color: '' },
  { emotion: 'Affectionate', color: '' },
  { emotion: 'Enthralled', color: '' },
  { emotion: 'Elation', color: '' },
  { emotion: 'Enthusiastic', color: '' },
  { emotion: 'Optimistic', color: '' },
  { emotion: 'Proud', color: '' },
  { emotion: 'Cheerful', color: '' },
  { emotion: 'Happy', color: '' },
  { emotion: 'Content', color: '' },
  { emotion: 'Moved', color: '' },
  { emotion: 'Overcome', color: '' },
  { emotion: 'Amazed', color: '' },
  { emotion: 'Confused', color: '' },
  { emotion: 'Stunned', color: '' },
  { emotion: 'Despair', color: '' },
  { emotion: 'Neglected', color: '' },
  { emotion: 'Shameful', color: '' },
  { emotion: 'Disappointed', color: '' },
  { emotion: 'Suffering', color: '' },
  { emotion: 'Disgust', color: '' },
  { emotion: 'Envy', color: '' },
  { emotion: 'Irritable', color: '' },
  { emotion: 'Exasperated', color: '' },
  { emotion: 'Rage', color: '' },
  { emotion: 'Horror', color: '' },
  { emotion: 'Nervous', color: '' },
  { emotion: 'Insecure', color: '' },
  { emotion: 'Terror', color: '' },
  { emotion: 'Scared', color: '' },
  { emotion: 'Satisfied', color: '' },
  { emotion: 'Relieved', color: '' },
  { emotion: 'Compassionate', color: '' },
  { emotion: 'Caring', color: '' },
  { emotion: 'Infatuation', color: '' },
  { emotion: 'Passion', color: '' },
  { emotion: 'Attracted', color: '' },
  { emotion: 'Sentimental', color: '' },
  { emotion: 'Fondness', color: '' },
  { emotion: 'Romantic', color: '' },
  { emotion: 'Rapture', color: '' },
  { emotion: 'Enchanted', color: '' },
  { emotion: 'Jubilation', color: '' },
  { emotion: 'Euphoric', color: '' },
  { emotion: 'Zeal', color: '' },
  { emotion: 'Excited', color: '' },
  { emotion: 'Hopeful', color: '' },
  { emotion: 'Eager', color: '' },
  { emotion: 'Illustrious', color: '' },
  { emotion: 'Triumphant', color: '' },
  { emotion: 'Blissful', color: '' },
  { emotion: 'Jovial', color: '' },
  { emotion: 'Delighted', color: '' },
  { emotion: 'Amused', color: '' },
  { emotion: 'Satisfied', color: '' },
  { emotion: 'Pleased', color: '' },
  { emotion: 'Touched', color: '' },
  { emotion: 'Stimulated', color: '' },
  { emotion: 'Astounded', color: '' },
  { emotion: 'Speechless', color: '' },
  { emotion: 'Awe-struck', color: '' },
  { emotion: 'Astonished', color: '' },
  { emotion: 'Perplexed', color: '' },
  { emotion: 'Disillusioned', color: '' },
  { emotion: 'Dismayed', color: '' },
  { emotion: 'Shocked', color: '' },
  { emotion: 'Powerless', color: '' },
  { emotion: 'Grief', color: '' },
  { emotion: 'Lonely', color: '' },
  { emotion: 'Isolated', color: '' },
  { emotion: 'Guilty', color: '' },
  { emotion: 'Regretful', color: '' },
  { emotion: 'Displeased', color: '' },
  { emotion: 'Dismayed', color: '' },
  { emotion: 'Sorrow', color: '' },
  { emotion: 'Depressed', color: '' },
  { emotion: 'Hurt', color: '' },
  { emotion: 'Agony', color: '' },
  { emotion: 'Revolted', color: '' },
  { emotion: 'Contempt', color: '' },
  { emotion: 'Jealous', color: '' },
  { emotion: 'Resentful', color: '' },
  { emotion: 'Aggravated', color: '' },
  { emotion: 'Annoyed', color: '' },
  { emotion: 'Frustrated', color: '' },
  { emotion: 'Agitated', color: '' },
  { emotion: 'Hostile', color: '' },
  { emotion: 'Hate', color: '' },
  { emotion: 'Dread', color: '' },
  { emotion: 'Mortified', color: '' },
  { emotion: 'Anxious', color: '' },
  { emotion: 'Worried', color: '' },
  { emotion: 'Inadequate', color: '' },
  { emotion: 'Inferior', color: '' },
  { emotion: 'Hysterical', color: '' },
  { emotion: 'Panic', color: '' },
  { emotion: 'Helpless', color: '' },
  { emotion: 'Frightened', color: '' },
];
